name: Lint Code / CI

on: [push, pull_request]

jobs:
  lint-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm cd client
      - run: npm run lint
    
  lint-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
           node-version: '18'
      - run: npm cd server
      - run: npm run lint