name: Test Backend (Node.js) / CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # O la versión que estés usando
      
      - name: Install dependencies (server)
        run: |
          cd server
          npm install

      - name: Run server tests
        run: |
          cd server 
          npm run test || true  
