name: Test Backend (Node.js) / CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # O la versión que estés usando

      - run: |
          cd server
          npm install
          npm run test || true
